---
- hosts: me
  remote_user: root

  tasks:
    - name: install {{ pkgname }} package
      yum: name={{ pkgname }}

    - name: start service
      service: name={{ pkgname }} state=started enabled=yes
