---
- hosts: me
  remote_user: root

  tasks:
    - name: create group
      group: name={{ item }}
      when: ansible_distribution_major_version == "7"
      with_items:
        - g1
        - g2
        - g3
    - name: install some packages
      yum: name={{ item }}

      with_items:
        - htop
        - tree
        - sl
        - hping3
